---
# tasks file for ansible-role-gridinit

- name: Include OS variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ openio_gridinit_packages }}"
  tags: install
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2

- name: Ensure directories exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ openio_gridinit_conf_confd }}"
    - "{{ openio_gridinit_rundir }}"
  tags: install

- name: Ensure sub-directory for namespace exists
  file:
    path: "{{ openio_gridinit_conf_confd }}/{{ item }}"
    state: directory
    mode: 0755
  with_items: "{{ openio_gridinit_services | map(attribute='namespace') | list }}"
  when: openio_gridinit_per_ns | bool
  tags: install

- name: Add gridinit global configuration file
  template:
    src: gridinit.conf.j2
    dest: "{{ openio_gridinit_config_file }}"
  tags: configure
  notify: reload gridinit

- name: Add gridinit per-service configuration file
  template:
    src: gridinit-service.j2
    dest: "{{ openio_gridinit_conf_confd + '/' + item.namespace + '/' + item.name + '.conf'
if openio_gridinit_per_ns else openio_gridinit_conf_confd + '/' + item.namespace + '-' + item.name + '.conf' }}"
  with_items: "{{ openio_gridinit_services }}"
  when: (item.state | default('present')) == 'present'
  tags: configure
  notify: reload gridinit

- name: Remove gridinit per-service configuration file
  file:
    path: "{{ openio_gridinit_conf_confd + '/' + item.namespace + '/' + item.name + '.conf'
if openio_gridinit_per_ns else openio_gridinit_conf_confd + '/' + item.namespace + '-' + item.name + '.conf' }}"
    state: absent
  with_items: "{{ openio_gridinit_services }}"
  when: (item.state | default('present')) == 'absent'
  tags: configure
  notify: reload gridinit

- name: Ensure service is started
  service:
    name: "{{ openio_gridinit_service_name }}"
    state: started
    enabled: "{{ openio_gridinit_enabled }}"
  tags: configure

...
